import { Lato, Federo } from "next/font/google";
import "./globals.css";
import type { Metadata } from "next";
import { ReactNode } from "react";

const LatoSans = Lato({
  weight: ["400"],
  subsets: ["latin"],
});

const FederoSans = Federo({
  variable: "--font-federo-sans",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${LatoSans.className} ${FederoSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
